version: "3.4"
services:
  cdn-backend:
    image: node:alpine
    container_name: cdn-backend
    entrypoint: /srv/app/deploy-runner.sh
    ports:
      - 10903:80
    working_dir: /srv/app
    environment:
      - CDN_URL=https://cdnapi.duartemartinho.com/api/
      - SERVER_PORT=80
    volumes:
      - type: bind
        source: ./backend
        target: /srv/app
    tty: true
  cdn-frontend:
    image: node:alpine
    container_name: cdn-frontend
    entrypoint: /bin/sh -c "npm i && npm run start"
    ports:
      - 10803:80
    working_dir: /srv/app
    environment:
      - VITE_API_URL=https://cdnapi.duartemartinho.com/api
    volumes:
      - type: bind
        source: ./frontend
        target: /srv/app
    tty: true