version: "3.4"
services:
  cdn-backend:
    image: node:alpine
    container_name: cdn-backend
    entrypoint: /bin/sh -c "/srv/app/deploy-runner.sh"
    ports:
      - 10903:80
    working_dir: /srv/app
    environment:
      - SERVER_PORT=80
    volumes:
      - type: bind
        source: .
        target: /srv/app
    tty: true